---
- name: Playbook3
  hosts: all
  become: yes
  become_user: root
  vars_prompt:
  - name: pack_name
    prompt: Give Package Name
    private: no
  tasks:
  - name: Install Package {{pack_name}}
    yum:
     name: "{{pack_name}}" 
     state: latest      
          
